[assets_figures_attractors_rossler_rossler_fig2]
key = "17715831962728535522"
assets = ["assets/figures/attractors/rossler/rossler_fig2.svg"]

[assets_figures_fractals_curves_curves_fig2]
key = "17759767035754928287"
assets = ["assets/figures/fractals/curves/curves_fig2.svg"]

[assets_figures_attractors_lorenz_lorenz_fig3]
key = "11098854109021323006"
assets = ["assets/figures/attractors/lorenz/lorenz_fig3.svg"]

[assets_figures_ising_snapshots_snapshots_fig1]
key = "194003530643818805"
assets = ["assets/figures/ising/snapshots/snapshots_fig1.svg"]

[assets_figures_ising_magnetization_magnetization_fig1]
key = "6451031763397345735"
assets = ["assets/figures/ising/magnetization/magnetization_fig1.svg"]

[assets_figures_ising_snapshots_snapshots_fig2]
key = "9742958386768002888"
assets = ["assets/figures/ising/snapshots/snapshots_fig2.svg"]

[assets_figures_fractals_curves_curves_fig1]
key = "11229655035480015512"
assets = ["assets/figures/fractals/curves/curves_fig1.svg"]

[assets_figures_ising_snapshots_snapshots_fig3]
key = "12587320145649052851"
assets = ["assets/figures/ising/snapshots/snapshots_fig3.svg"]

[assets_figures_fractals_koch_koch_fig1]
key = "5854365264458024906"
assets = ["assets/figures/fractals/koch/koch_fig1.svg"]

[assets_figures_attractors_rossler_rossler_fig3]
key = "4156359900442498107"
assets = ["assets/figures/attractors/rossler/rossler_fig3.svg"]

[assets_figures_fractals_koch_koch_fig2]
key = "11603439894471585180"
assets = ["assets/figures/fractals/koch/koch_fig2.svg"]

[assets_figures_fractals_koch_koch_fig3]
key = "6948569472532824585"
assets = ["assets/figures/fractals/koch/koch_fig3.svg"]

[assets_figures_attractors_lorenz_lorenz_fig1]
key = "6560626657612836280"
assets = ["assets/figures/attractors/lorenz/lorenz_fig1.svg"]

[assets_figures_fractals_curves_curves_fig3]
key = "6243268056847430080"
assets = ["assets/figures/fractals/curves/curves_fig3.svg"]

[assets_figures_attractors_lorenz_lorenz_fig2]
key = "5285552412557148967"
assets = ["assets/figures/attractors/lorenz/lorenz_fig2.svg"]

[assets_figures_attractors_rossler_rossler_fig1]
key = "469352562569196079"
assets = ["assets/figures/attractors/rossler/rossler_fig1.svg"]
