[assets_figures_ising_magnetization_magnetization_fig1]
assets = ["assets/figures/ising/magnetization/magnetization_fig1.svg"]
key = "9650777677222241367"

[assets_figures_fractals_koch_koch_fig2]
assets = ["assets/figures/fractals/koch/koch_fig2.svg"]
key = "2278480250791806452"

[assets_figures_fractals_curves_curves_fig2]
assets = ["assets/figures/fractals/curves/curves_fig2.svg"]
key = "858553945307169039"

[assets_figures_fractals_koch_koch_fig3]
assets = ["assets/figures/fractals/koch/koch_fig3.svg"]
key = "15651390996702131197"

[assets_figures_attractors_lorenz_lorenz_fig1]
assets = ["assets/figures/attractors/lorenz/lorenz_fig1.svg"]
key = "8090713534257672684"

[assets_figures_attractors_rossler_rossler_fig2]
assets = ["assets/figures/attractors/rossler/rossler_fig2.svg"]
key = "17308904936857713432"

[assets_figures_fractals_curves_curves_fig1]
assets = ["assets/figures/fractals/curves/curves_fig1.svg"]
key = "4946029671456074529"

[assets_figures_ising_dynamics_dynamics_system_T_2_27__sample_1]
assets = ["assets/figures/ising/dynamics/dynamics_system_T_2_27__sample_1.gif"]
key = "16729635603851436543"

[assets_figures_attractors_lorenz_lorenz_fig2]
assets = ["assets/figures/attractors/lorenz/lorenz_fig2.svg"]
key = "928395089261489386"

[assets_figures_fractals_koch_koch_fig1]
assets = ["assets/figures/fractals/koch/koch_fig1.svg"]
key = "14898794113231730345"

[assets_figures_attractors_rossler_rossler_fig1]
assets = ["assets/figures/attractors/rossler/rossler_fig1.svg"]
key = "11296541113319536178"

[assets_figures_fractals_curves_curves_fig3]
assets = ["assets/figures/fractals/curves/curves_fig3.svg"]
key = "12759831972172919973"

[assets_figures_attractors_lorenz_lorenz_fig3]
assets = ["assets/figures/attractors/lorenz/lorenz_fig3.svg"]
key = "2302342124608047297"
